spring.application.name=iron-secretary-backend

# Security: Never hardcode API keys here.
# Pass them via Environment Variable: GEMINI_API_KEY
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY}

